CREATE TABLE IF NOT EXISTS spaces(
    id UUID NOT NULL PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS questions(
    id UUID NOT NULL PRIMARY KEY,
    author_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    space_id UUID REFERENCES spaces(id) ON DELETE CASCADE DEFAULT NULL,
    question TEXT,
    upvote INT NOT NULL DEFAULT 0,
    downvote INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);