version: '3'

services:
  pgquora:
    container_name: pgquora
    image: postgres:15
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pgquora
      POSTGRES_PASSWORD: pgquora
      POSTGRES_DB: pgquora
  jaeger:
    image: jaegertracing/all-in-one:1.49
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411